# Stage 1: Build the Angular application
FROM node:18 AS build
WORKDIR /app
COPY ./src/ .
RUN npm install
RUN npm run build --prod

# Stage 2: Serve Angular app with Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
